server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  ###consul注册中心地址
  cloud:
    consul:
      host: 47.104.155.151
      port: 8500
      discovery:
        service-name: ${spring.application.name}
management:
  endpoint:
    health:
      show-details: always
