server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  ###consul注册中心地址
  cloud:
    consul:
      host: 47.104.155.151
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        healthCHeckInterval: ${management.context-path}/healt
